### ISSUE TITLE
iOS: disable bounce scrolling where not appropriate

### ISSUE THREAD

**Issue by Simon-Laux** [webxdc/timetracking-webxdc#17]
on iOS you can bounce scroll the whole page, which also moves the tab bar and everything. we should deny that and only allow bounce scrolling on areas that are actually scrollable

**Comment by r10s** [comment]
for the calendar, we just added `overscroll-behavior: none` to css, that seems to be good enough meanwhile, cmp https://codeberg.org/webxdc/calendar/commit/60375dd1f6665aaad4c9dc4bcd24036e3cdbe315 (me trying to work partly with codeberg :)
